[View in Colaboratory](https://colab.research.google.com/github/mdsamad001/ML-for-small-dataset/blob/master/test_colab.ipynb)

This is a test code

In [0]:
import numpy as np

df = np.zeros((4,5))

print (df)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
import pandas as pd

d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
      'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

dg = pd.DataFrame(d)

dg

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0